// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"
	"net/netip"
	"time"

	"github.com/bbxx111/accountkit/enum"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertAuditEvents = `-- name: InsertAuditEvents :batchexec

INSERT INTO audit_event (id, event_type, actor_kind, user_id, admin_issuer, admin_subject, admin_username,
                         session_id, identity_kind, subject_hint, result, reason, ip, device_id, request_id, occur_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertAuditEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertAuditEventsParams struct {
	ID            string
	EventType     enum.EventType
	ActorKind     enum.ActorKind
	UserID        *string
	AdminIssuer   *string
	AdminSubject  *string
	AdminUsername *string
	SessionID     *string
	IdentityKind  *enum.IdentityKind
	SubjectHint   *string
	Result        enum.Result
	Reason        *string
	Ip            *netip.Addr
	DeviceID      *string
	RequestID     *string
	OccurTime     time.Time
}

// audit_event：审计事件的写入与保留期清理（读侧的管理端分页在阶段 6）。
// 排序约定（§3.4 勘误）：ORDER BY occur_time, id；索引 audit_event_user_id_occur_time_idx (user_id, occur_time, id)。
func (q *Queries) InsertAuditEvents(ctx context.Context, arg []InsertAuditEventsParams) *InsertAuditEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.EventType,
			a.ActorKind,
			a.UserID,
			a.AdminIssuer,
			a.AdminSubject,
			a.AdminUsername,
			a.SessionID,
			a.IdentityKind,
			a.SubjectHint,
			a.Result,
			a.Reason,
			a.Ip,
			a.DeviceID,
			a.RequestID,
			a.OccurTime,
		}
		batch.Queue(insertAuditEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertAuditEventsBatchResults{br, len(arg), false}
}

func (b *InsertAuditEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertAuditEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
