// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/bbxx111/accountkit/enum"
)

type AuditEvent struct {
	ID            string
	EventType     enum.EventType
	ActorKind     enum.ActorKind
	UserID        *string
	AdminIssuer   *string
	AdminSubject  *string
	AdminUsername *string
	SessionID     *string
	IdentityKind  *enum.IdentityKind
	SubjectHint   *string
	Result        enum.Result
	Reason        *string
	Ip            *netip.Addr
	DeviceID      *string
	RequestID     *string
	OccurTime     time.Time
}

type Identity struct {
	ID                string
	UserID            string
	Kind              int16
	SubjectDigest     *string
	DigestKeyVersion  *int16
	ProviderSubject   *string
	SubjectCiphertext []byte
	CipherKeyVersion  *int16
	HintPrefix        *string
	HintSuffix        *string
	ProviderMeta      []byte
	CreateTime        time.Time
	UpdateTime        time.Time
	DeleteTime        *time.Time
}

type Session struct {
	ID                       string
	UserID                   string
	DeviceID                 string
	DeviceName               *string
	AuthTime                 time.Time
	RefreshTokenHash         []byte
	PreviousRefreshTokenHash []byte
	RotateTime               *time.Time
	RefreshExpireTime        time.Time
	LastUsedTime             time.Time
	RevokeTime               *time.Time
	RevokeReason             *int16
	CreateTime               time.Time
	UpdateTime               time.Time
}

type UserAccount struct {
	ID                  string
	State               int16
	DisplayName         *string
	FreezeTime          *time.Time
	FreezeReason        *string
	FreezeActorSubject  *string
	FreezeActorUsername *string
	DeleteTime          *time.Time
	PurgeTime           *time.Time
	CreateTime          time.Time
	UpdateTime          time.Time
}
