// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const deleteAuditEventsBefore = `-- name: DeleteAuditEventsBefore :execrows
DELETE FROM audit_event
WHERE id IN (
    SELECT id FROM audit_event WHERE occur_time < $1::timestamptz ORDER BY occur_time LIMIT $2::int
)
`

type DeleteAuditEventsBeforeParams struct {
	Before    time.Time
	BatchSize int32
}

// 维护任务 audit_retention：按 occur_time 分批删除超过保留期的行；命中 audit_event_occur_time_idx。
func (q *Queries) DeleteAuditEventsBefore(ctx context.Context, arg DeleteAuditEventsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditEventsBefore, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditEventsByUser = `-- name: ListAuditEventsByUser :many
SELECT id, event_type, actor_kind, user_id, admin_issuer, admin_subject, admin_username, session_id, identity_kind, subject_hint, result, reason, ip, device_id, request_id, occur_time FROM audit_event
WHERE user_id = $1::text
  AND ($2::timestamptz IS NULL
       OR (occur_time, id) > ($2::timestamptz, $3::text))
ORDER BY occur_time, id
LIMIT $4::int
`

type ListAuditEventsByUserParams struct {
	UserID    string
	AfterTime *time.Time
	AfterID   *string
	PageLimit int32
}

// 管理端 GET /users/{user}/auditEvents：keyset 分页 ORDER BY occur_time, id；命中 audit_event_user_id_occur_time_idx。
func (q *Queries) ListAuditEventsByUser(ctx context.Context, arg ListAuditEventsByUserParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByUser,
		arg.UserID,
		arg.AfterTime,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorKind,
			&i.UserID,
			&i.AdminIssuer,
			&i.AdminSubject,
			&i.AdminUsername,
			&i.SessionID,
			&i.IdentityKind,
			&i.SubjectHint,
			&i.Result,
			&i.Reason,
			&i.Ip,
			&i.DeviceID,
			&i.RequestID,
			&i.OccurTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
