// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/bbxx111/accountkit/enum"
)

const anonymizeIdentity = `-- name: AnonymizeIdentity :execrows
UPDATE identity
SET subject_digest     = CASE WHEN subject_digest   IS NULL THEN NULL ELSE $1::text END,
    provider_subject   = CASE WHEN provider_subject IS NULL THEN NULL ELSE $1::text END,
    digest_key_version = NULL, cipher_key_version = NULL, subject_ciphertext = NULL,
    provider_meta = NULL, hint_prefix = NULL, hint_suffix = NULL,
    delete_time = COALESCE(delete_time, $2::timestamptz), update_time = $2::timestamptz
WHERE id = $3 AND user_id = $4
`

type AnonymizeIdentityParams struct {
	Replacement string
	Now         time.Time
	ID          string
	UserID      string
}

// purge：用随机值替换 subject_digest / provider_subject（哪个非空替换哪个，保持 identity_subject_exactly_one），
// 其余 PII 与密钥版本置 NULL；未软删的行同时软删。
func (q *Queries) AnonymizeIdentity(ctx context.Context, arg AnonymizeIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, anonymizeIdentity,
		arg.Replacement,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveSessionsByUser = `-- name: CountActiveSessionsByUser :one
SELECT count(*) FROM session
WHERE user_id = $1 AND revoke_time IS NULL AND refresh_expire_time > $2::timestamptz
`

type CountActiveSessionsByUserParams struct {
	UserID string
	Now    time.Time
}

// 管理端用户详情：活跃会话数；命中 session_user_id_idx。
func (q *Queries) CountActiveSessionsByUser(ctx context.Context, arg CountActiveSessionsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUser, arg.UserID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentity = `-- name: CreateIdentity :one

INSERT INTO identity (id, user_id, kind, subject_digest, digest_key_version, provider_subject,
                      subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time
`

type CreateIdentityParams struct {
	ID                string
	UserID            string
	Kind              enum.IdentityKind
	SubjectDigest     *string
	DigestKeyVersion  *int16
	ProviderSubject   *string
	SubjectCiphertext []byte
	CipherKeyVersion  *int16
	HintPrefix        *string
	HintSuffix        *string
	ProviderMeta      []byte
}

// identity
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.SubjectDigest,
		arg.DigestKeyVersion,
		arg.ProviderSubject,
		arg.SubjectCiphertext,
		arg.CipherKeyVersion,
		arg.HintPrefix,
		arg.HintSuffix,
		arg.ProviderMeta,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SubjectDigest,
		&i.DigestKeyVersion,
		&i.ProviderSubject,
		&i.SubjectCiphertext,
		&i.CipherKeyVersion,
		&i.HintPrefix,
		&i.HintSuffix,
		&i.ProviderMeta,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeleteTime,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO session (id, user_id, device_id, device_name, auth_time, refresh_token_hash, refresh_expire_time, last_used_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $5)
RETURNING id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time
`

type CreateSessionParams struct {
	ID                string
	UserID            string
	DeviceID          string
	DeviceName        *string
	AuthTime          time.Time
	RefreshTokenHash  []byte
	RefreshExpireTime time.Time
}

// session
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceName,
		arg.AuthTime,
		arg.RefreshTokenHash,
		arg.RefreshExpireTime,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.AuthTime,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.RotateTime,
		&i.RefreshExpireTime,
		&i.LastUsedTime,
		&i.RevokeTime,
		&i.RevokeReason,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO user_account (id, state) VALUES ($1, $2)
RETURNING id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time
`

type CreateUserParams struct {
	ID    string
	State enum.UserState
}

// user_account
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.State)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :execrows
DELETE FROM session
WHERE id IN (
    SELECT id FROM session
    WHERE (revoke_time IS NOT NULL AND revoke_time < $1::timestamptz)
       OR (revoke_time IS NULL AND refresh_expire_time < $1::timestamptz)
    LIMIT $2::int
)
`

type DeleteStaleSessionsParams struct {
	Before    time.Time
	BatchSize int32
}

// 维护任务 cleanup_sessions：物理删除吊销/过期超过保留期的会话；子查询限批，避免单事务锁太多行。
// 两个 OR 分支分别命中 session_revoke_time_idx / session_refresh_expire_time_idx。
func (q *Queries) DeleteStaleSessions(ctx context.Context, arg DeleteStaleSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleSessions, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveIdentityByDigests = `-- name: FindActiveIdentityByDigests :one
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity
WHERE kind = $1 AND subject_digest = ANY($2::text[]) AND delete_time IS NULL
LIMIT 1
`

type FindActiveIdentityByDigestsParams struct {
	Kind    enum.IdentityKind
	Digests []string
}

// 多版本查找：@digests 是 pii.Digester.AllDigests 的结果（active 在前）。漏掉任一活跃版本
// 会让该版本下写入的行查不到，同一手机号就会被再次注册。命中 identity_kind_subject_digest_uidx。
func (q *Queries) FindActiveIdentityByDigests(ctx context.Context, arg FindActiveIdentityByDigestsParams) (Identity, error) {
	row := q.db.QueryRow(ctx, findActiveIdentityByDigests, arg.Kind, arg.Digests)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SubjectDigest,
		&i.DigestKeyVersion,
		&i.ProviderSubject,
		&i.SubjectCiphertext,
		&i.CipherKeyVersion,
		&i.HintPrefix,
		&i.HintSuffix,
		&i.ProviderMeta,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeleteTime,
	)
	return i, err
}

const findActiveIdentityByProviderSubject = `-- name: FindActiveIdentityByProviderSubject :one
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity WHERE kind = $1 AND provider_subject = $2 AND delete_time IS NULL
`

type FindActiveIdentityByProviderSubjectParams struct {
	Kind            enum.IdentityKind
	ProviderSubject *string
}

func (q *Queries) FindActiveIdentityByProviderSubject(ctx context.Context, arg FindActiveIdentityByProviderSubjectParams) (Identity, error) {
	row := q.db.QueryRow(ctx, findActiveIdentityByProviderSubject, arg.Kind, arg.ProviderSubject)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SubjectDigest,
		&i.DigestKeyVersion,
		&i.ProviderSubject,
		&i.SubjectCiphertext,
		&i.CipherKeyVersion,
		&i.HintPrefix,
		&i.HintSuffix,
		&i.ProviderMeta,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeleteTime,
	)
	return i, err
}

const freezeUser = `-- name: FreezeUser :one
UPDATE user_account
SET state = $1, freeze_time = $2::timestamptz, freeze_reason = $3::text,
    freeze_actor_subject = $4::text, freeze_actor_username = $5::text,
    update_time = $2::timestamptz
WHERE id = $6
RETURNING id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time
`

type FreezeUserParams struct {
	State         enum.UserState
	Now           time.Time
	Reason        string
	ActorSubject  string
	ActorUsername string
	ID            string
}

// 管理端 :freeze：调用方持行锁并已确认 state = ACTIVE；快照管理员 sub/username（issuer 进审计）。
func (q *Queries) FreezeUser(ctx context.Context, arg FreezeUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, freezeUser,
		arg.State,
		arg.Now,
		arg.Reason,
		arg.ActorSubject,
		arg.ActorUsername,
		arg.ID,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getActiveIdentityByIDAndUser = `-- name: GetActiveIdentityByIDAndUser :one
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity WHERE id = $1 AND user_id = $2 AND delete_time IS NULL
`

type GetActiveIdentityByIDAndUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetActiveIdentityByIDAndUser(ctx context.Context, arg GetActiveIdentityByIDAndUserParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getActiveIdentityByIDAndUser, arg.ID, arg.UserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SubjectDigest,
		&i.DigestKeyVersion,
		&i.ProviderSubject,
		&i.SubjectCiphertext,
		&i.CipherKeyVersion,
		&i.HintPrefix,
		&i.HintSuffix,
		&i.ProviderMeta,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeleteTime,
	)
	return i, err
}

const getActiveSessionByIDAndUser = `-- name: GetActiveSessionByIDAndUser :one
SELECT id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time FROM session WHERE id = $1 AND user_id = $2 AND revoke_time IS NULL
`

type GetActiveSessionByIDAndUserParams struct {
	ID     string
	UserID string
}

// 明确撤销定位未吊销记录，不能因为刷新期限已到而遗漏仍有效的 access。
func (q *Queries) GetActiveSessionByIDAndUser(ctx context.Context, arg GetActiveSessionByIDAndUserParams) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByIDAndUser, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.AuthTime,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.RotateTime,
		&i.RefreshExpireTime,
		&i.LastUsedTime,
		&i.RevokeTime,
		&i.RevokeReason,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getActiveSessionByUserDevice = `-- name: GetActiveSessionByUserDevice :one
SELECT id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time FROM session WHERE user_id = $1 AND device_id = $2 AND revoke_time IS NULL
ORDER BY create_time DESC, id DESC LIMIT 1
`

type GetActiveSessionByUserDeviceParams struct {
	UserID   string
	DeviceID string
}

// 同一设备再次登录：先吊销旧会话（REPLACED_BY_RELOGIN）再建新会话。
// 此处定位未吊销记录，包含刷新期限已到但尚未清理的会话。
func (q *Queries) GetActiveSessionByUserDevice(ctx context.Context, arg GetActiveSessionByUserDeviceParams) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByUserDevice, arg.UserID, arg.DeviceID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.AuthTime,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.RotateTime,
		&i.RefreshExpireTime,
		&i.LastUsedTime,
		&i.RevokeTime,
		&i.RevokeReason,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getSessionByPreviousRefreshHash = `-- name: GetSessionByPreviousRefreshHash :one
SELECT id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time FROM session WHERE previous_refresh_token_hash = $1
`

func (q *Queries) GetSessionByPreviousRefreshHash(ctx context.Context, previousRefreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByPreviousRefreshHash, previousRefreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.AuthTime,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.RotateTime,
		&i.RefreshExpireTime,
		&i.LastUsedTime,
		&i.RevokeTime,
		&i.RevokeReason,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time FROM session WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.AuthTime,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.RotateTime,
		&i.RefreshExpireTime,
		&i.LastUsedTime,
		&i.RevokeTime,
		&i.RevokeReason,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time FROM user_account WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const listActiveCipherKeyVersions = `-- name: ListActiveCipherKeyVersions :many
SELECT DISTINCT cipher_key_version::smallint AS version FROM identity
WHERE delete_time IS NULL AND cipher_key_version IS NOT NULL
ORDER BY 1
`

func (q *Queries) ListActiveCipherKeyVersions(ctx context.Context) ([]int16, error) {
	rows, err := q.db.Query(ctx, listActiveCipherKeyVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var version int16
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDigestKeyVersions = `-- name: ListActiveDigestKeyVersions :many
SELECT DISTINCT digest_key_version::smallint AS version FROM identity
WHERE delete_time IS NULL AND digest_key_version IS NOT NULL
ORDER BY 1
`

// 启动期校验（Migrate → CheckKeyVersions）：活跃锚点身份实际使用的 HMAC 版本集合。
func (q *Queries) ListActiveDigestKeyVersions(ctx context.Context) ([]int16, error) {
	rows, err := q.db.Query(ctx, listActiveDigestKeyVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var version int16
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveIdentitiesByUser = `-- name: ListActiveIdentitiesByUser :many
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity WHERE user_id = $1 AND delete_time IS NULL ORDER BY create_time, id
`

func (q *Queries) ListActiveIdentitiesByUser(ctx context.Context, userID string) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listActiveIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SubjectDigest,
			&i.DigestKeyVersion,
			&i.ProviderSubject,
			&i.SubjectCiphertext,
			&i.CipherKeyVersion,
			&i.HintPrefix,
			&i.HintSuffix,
			&i.ProviderMeta,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DeleteTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time FROM session
WHERE user_id = $1 AND revoke_time IS NULL AND refresh_expire_time > $2::timestamptz
ORDER BY create_time, id
`

type ListActiveSessionsByUserParams struct {
	UserID string
	Now    time.Time
}

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, arg ListActiveSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceName,
			&i.AuthTime,
			&i.RefreshTokenHash,
			&i.PreviousRefreshTokenHash,
			&i.RotateTime,
			&i.RefreshExpireTime,
			&i.LastUsedTime,
			&i.RevokeTime,
			&i.RevokeReason,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByCipherKeyVersion = `-- name: ListIdentitiesByCipherKeyVersion :many
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity
WHERE delete_time IS NULL AND cipher_key_version = $1::smallint
ORDER BY create_time, id
LIMIT $2::int
`

type ListIdentitiesByCipherKeyVersionParams struct {
	Version   int16
	BatchSize int32
}

// 维护任务 reencrypt_subjects：仍用旧加密版本的活跃锚点身份；命中 identity_cipher_key_version_idx。
func (q *Queries) ListIdentitiesByCipherKeyVersion(ctx context.Context, arg ListIdentitiesByCipherKeyVersionParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByCipherKeyVersion, arg.Version, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SubjectDigest,
			&i.DigestKeyVersion,
			&i.ProviderSubject,
			&i.SubjectCiphertext,
			&i.CipherKeyVersion,
			&i.HintPrefix,
			&i.HintSuffix,
			&i.ProviderMeta,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DeleteTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByDigestKeyVersion = `-- name: ListIdentitiesByDigestKeyVersion :many
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity
WHERE delete_time IS NULL AND digest_key_version = $1::smallint
ORDER BY create_time, id
LIMIT $2::int
`

type ListIdentitiesByDigestKeyVersionParams struct {
	Version   int16
	BatchSize int32
}

// 维护任务 rekey_digests：仍用旧 HMAC 版本的活跃锚点身份；命中 identity_digest_key_version_idx。
func (q *Queries) ListIdentitiesByDigestKeyVersion(ctx context.Context, arg ListIdentitiesByDigestKeyVersionParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByDigestKeyVersion, arg.Version, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SubjectDigest,
			&i.DigestKeyVersion,
			&i.ProviderSubject,
			&i.SubjectCiphertext,
			&i.CipherKeyVersion,
			&i.HintPrefix,
			&i.HintSuffix,
			&i.ProviderMeta,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DeleteTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByUserIncludingDeleted = `-- name: ListIdentitiesByUserIncludingDeleted :many
SELECT id, user_id, kind, subject_digest, digest_key_version, provider_subject, subject_ciphertext, cipher_key_version, hint_prefix, hint_suffix, provider_meta, create_time, update_time, delete_time FROM identity WHERE user_id = $1 ORDER BY create_time, id
`

// purge 专用：含已解绑（软删）的行——它们仍带原 subject 的摘要/密文/hint，必须一并匿名化。命中 identity_user_id_idx。
func (q *Queries) ListIdentitiesByUserIncludingDeleted(ctx context.Context, userID string) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUserIncludingDeleted, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SubjectDigest,
			&i.DigestKeyVersion,
			&i.ProviderSubject,
			&i.SubjectCiphertext,
			&i.CipherKeyVersion,
			&i.HintPrefix,
			&i.HintSuffix,
			&i.ProviderMeta,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DeleteTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT u.id, u.state, u.display_name, u.freeze_time, u.freeze_reason, u.freeze_actor_subject, u.freeze_actor_username, u.delete_time, u.purge_time, u.create_time, u.update_time FROM user_account u
WHERE ($1::smallint IS NULL OR u.state = $1::smallint)
  AND ($2::bool OR u.state NOT IN (3, 4))
  AND ($3::timestamptz IS NULL OR u.create_time >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR u.create_time <  $4::timestamptz)
  AND (NOT $5::bool OR EXISTS (
        SELECT 1 FROM identity i
        WHERE i.user_id = u.id AND i.delete_time IS NULL
          AND ($6::smallint IS NULL OR i.kind = $6::smallint)
          AND (cardinality($7::text[]) = 0 OR i.subject_digest = ANY($7::text[]))
          AND ($8::text IS NULL OR i.hint_prefix = $8::text)
          AND ($9::text IS NULL OR i.hint_suffix = $9::text)))
  AND ($10::timestamptz IS NULL
       OR (u.create_time, u.id) > ($10::timestamptz, $11::text))
ORDER BY u.create_time, u.id
LIMIT $12::int
`

type ListUsersAdminParams struct {
	State          *int16
	IncludeDeleted bool
	CreateTimeMin  *time.Time
	CreateTimeMax  *time.Time
	ByIdentity     bool
	IdentityKind   *int16
	Digests        []string
	HintPrefix     *string
	HintSuffix     *string
	AfterTime      *time.Time
	AfterID        *string
	PageLimit      int32
}

// 管理端 GET /users：可空参数实现可选过滤（sqlc.narg），keyset 分页 ORDER BY create_time, id（§3.4），
// 由 user_account_create_time_id_idx 提供索引序，避免每页全表排序。
// state NOT IN (3, 4) 写死数值（PENDING_DELETION / DELETED，与 enum 钉死），与 purge 索引谓词同理。
// 身份条件落在同一条活跃身份行（单个 EXISTS）；identity.phone/email 的 digests 是 AllDigests 的结果。
// 注意：EXISTS 子查询里的 ($n IS NULL OR col = $n) 形式在 PostgreSQL 通用计划（generic plan）下可能不走
// identity_kind_* 的部分索引；若观测到这类退化，优先在连接池上设 plan_cache_mode = force_custom_plan，
// 或对本查询 SET LOCAL。
func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]UserAccount, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin,
		arg.State,
		arg.IncludeDeleted,
		arg.CreateTimeMin,
		arg.CreateTimeMax,
		arg.ByIdentity,
		arg.IdentityKind,
		arg.Digests,
		arg.HintPrefix,
		arg.HintSuffix,
		arg.AfterTime,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccount
	for rows.Next() {
		var i UserAccount
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.DisplayName,
			&i.FreezeTime,
			&i.FreezeReason,
			&i.FreezeActorSubject,
			&i.FreezeActorUsername,
			&i.DeleteTime,
			&i.PurgeTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersDueForPurge = `-- name: ListUsersDueForPurge :many
SELECT id FROM user_account
WHERE state = 3 AND purge_time <= $1::timestamptz
ORDER BY purge_time, id
LIMIT $2::int
`

type ListUsersDueForPurgeParams struct {
	Now       time.Time
	BatchSize int32
}

// purge 任务取批。谓词写死 state = 3（PENDING_DELETION）而非绑定参数：它必须与 user_account_purge_time_idx
// 的部分索引谓词逐字一致——通用计划下绑定参数无法证明蕴含部分索引谓词，会退化为全表扫描。
func (q *Queries) ListUsersDueForPurge(ctx context.Context, arg ListUsersDueForPurgeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsersDueForPurge, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionByID = `-- name: LockSessionByID :one
SELECT id, user_id, device_id, device_name, auth_time, refresh_token_hash, previous_refresh_token_hash, rotate_time, refresh_expire_time, last_used_time, revoke_time, revoke_reason, create_time, update_time FROM session WHERE id = $1 FOR UPDATE
`

// 轮换前对会话行加锁：并发刷新在此串行化，CAS 失败者等到胜者提交（含宽限缓存写入）后再走宽限路径。
func (q *Queries) LockSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, lockSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.AuthTime,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.RotateTime,
		&i.RefreshExpireTime,
		&i.LastUsedTime,
		&i.RevokeTime,
		&i.RevokeReason,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const lockUserByID = `-- name: LockUserByID :one
SELECT id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time FROM user_account WHERE id = $1 FOR UPDATE
`

// 同设备重登前对用户行加锁：并发登录在此串行化，第二个事务等到第一个提交（含会话吊销/新建）
// 后再读，从而看到刚吊销的旧会话，不会与它一起并存两条活跃会话。
func (q *Queries) LockUserByID(ctx context.Context, id string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, lockUserByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const purgeUser = `-- name: PurgeUser :execrows
UPDATE user_account
SET state = $1, display_name = NULL, freeze_time = NULL, freeze_reason = NULL,
    freeze_actor_subject = NULL, freeze_actor_username = NULL,
    purge_time = $2::timestamptz, update_time = $2::timestamptz
WHERE id = $3 AND state = $4
`

type PurgeUserParams struct {
	DeletedState enum.UserState
	Now          time.Time
	ID           string
	PendingState enum.UserState
}

// 匿名化账号行：展示名与冻结快照置 NULL，state → DELETED，purge_time 改写为实际执行时刻（delete_time 保留）。
// WHERE 带 state 做二次保险：调用方持锁并已复核状态，这里再钉一次避免把非 PENDING_DELETION 的行写成 DELETED。
func (q *Queries) PurgeUser(ctx context.Context, arg PurgeUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUser,
		arg.DeletedState,
		arg.Now,
		arg.ID,
		arg.PendingState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE session SET revoke_time = $1::timestamptz, revoke_reason = $2, update_time = $1::timestamptz
WHERE id = $3 AND revoke_time IS NULL
`

type RevokeSessionParams struct {
	Now    time.Time
	Reason *enum.RevokeReason
	ID     string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.Now, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsByUser = `-- name: RevokeSessionsByUser :many
UPDATE session SET revoke_time = $1::timestamptz, revoke_reason = $2, update_time = $1::timestamptz
WHERE user_id = $3 AND revoke_time IS NULL AND ($4::text IS NULL OR id <> $4::text)
RETURNING id
`

type RevokeSessionsByUserParams struct {
	Now      time.Time
	Reason   *enum.RevokeReason
	UserID   string
	ExceptID *string
}

// 吊销该用户全部未吊销会话（包含到期行），可排除一个（revokeOthers 保留当前）。返回被吊销的 sid 供写入吊销集。
func (q *Queries) RevokeSessionsByUser(ctx context.Context, arg RevokeSessionsByUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeSessionsByUser,
		arg.Now,
		arg.Reason,
		arg.UserID,
		arg.ExceptID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateSession = `-- name: RotateSession :execrows
UPDATE session
SET refresh_token_hash = $1, previous_refresh_token_hash = $2,
    rotate_time = $3::timestamptz, refresh_expire_time = $4,
    last_used_time = $3::timestamptz, update_time = $3::timestamptz
WHERE id = $5 AND refresh_token_hash = $2 AND revoke_time IS NULL
  AND refresh_expire_time > $3::timestamptz
`

type RotateSessionParams struct {
	NewHash           []byte
	OldHash           []byte
	Now               time.Time
	RefreshExpireTime time.Time
	ID                string
}

// CAS：只有当前哈希仍等于调用方读到的旧哈希时才轮换；并发刷新中只有一个成功，
// 其余走宽限路径。旧哈希进入 previous_refresh_token_hash 供重放识别。
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSession,
		arg.NewHash,
		arg.OldHash,
		arg.Now,
		arg.RefreshExpireTime,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubAuditEventsByUser = `-- name: ScrubAuditEventsByUser :execrows

UPDATE audit_event SET ip = NULL, device_id = NULL, subject_hint = NULL
WHERE user_id = $1::text AND (ip IS NOT NULL OR device_id IS NOT NULL OR subject_hint IS NOT NULL)
`

// audit_event
// purge：去掉可关联到自然人的请求侧字段，保留事件与 user_id（§3.5）。命中 audit_event_user_id_occur_time_idx 前缀。
func (q *Queries) ScrubAuditEventsByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubAuditEventsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteIdentity = `-- name: SoftDeleteIdentity :execrows
UPDATE identity SET delete_time = $1::timestamptz, update_time = $1::timestamptz
WHERE id = $2 AND user_id = $3 AND delete_time IS NULL
`

type SoftDeleteIdentityParams struct {
	Now    time.Time
	ID     string
	UserID string
}

func (q *Queries) SoftDeleteIdentity(ctx context.Context, arg SoftDeleteIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteIdentity, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE user_account
SET state = $1, delete_time = $2::timestamptz, purge_time = $3::timestamptz, update_time = $2::timestamptz
WHERE id = $4
RETURNING id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time
`

type SoftDeleteUserParams struct {
	State     enum.UserState
	Now       time.Time
	PurgeTime time.Time
	ID        string
}

// 软删除（AIP-164）：调用方须已持有行锁并确认 state = ACTIVE。
func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, softDeleteUser,
		arg.State,
		arg.Now,
		arg.PurgeTime,
		arg.ID,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const undeleteUser = `-- name: UndeleteUser :one
UPDATE user_account
SET state = $1, delete_time = NULL, purge_time = NULL, update_time = $2::timestamptz
WHERE id = $3
RETURNING id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time
`

type UndeleteUserParams struct {
	State enum.UserState
	Now   time.Time
	ID    string
}

// 取消注销：调用方须已持有行锁并确认 state = PENDING_DELETION。
func (q *Queries) UndeleteUser(ctx context.Context, arg UndeleteUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, undeleteUser, arg.State, arg.Now, arg.ID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const unfreezeUser = `-- name: UnfreezeUser :one
UPDATE user_account
SET state = $1, freeze_time = NULL, freeze_reason = NULL, freeze_actor_subject = NULL, freeze_actor_username = NULL,
    update_time = $2::timestamptz
WHERE id = $3
RETURNING id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time
`

type UnfreezeUserParams struct {
	State enum.UserState
	Now   time.Time
	ID    string
}

// 管理端 :unfreeze：调用方持行锁并已确认 state = FROZEN；快照清空，历史留在审计。
func (q *Queries) UnfreezeUser(ctx context.Context, arg UnfreezeUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, unfreezeUser, arg.State, arg.Now, arg.ID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateIdentityCiphertext = `-- name: UpdateIdentityCiphertext :execrows
UPDATE identity
SET subject_ciphertext = $1, cipher_key_version = $2::smallint, update_time = $3::timestamptz
WHERE id = $4 AND cipher_key_version = $5::smallint AND delete_time IS NULL
`

type UpdateIdentityCiphertextParams struct {
	Ciphertext []byte
	Version    int16
	Now        time.Time
	ID         string
	OldVersion int16
}

func (q *Queries) UpdateIdentityCiphertext(ctx context.Context, arg UpdateIdentityCiphertextParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentityCiphertext,
		arg.Ciphertext,
		arg.Version,
		arg.Now,
		arg.ID,
		arg.OldVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIdentityDigest = `-- name: UpdateIdentityDigest :execrows
UPDATE identity
SET subject_digest = $1::text, digest_key_version = $2::smallint, update_time = $3::timestamptz
WHERE id = $4 AND digest_key_version = $5::smallint AND delete_time IS NULL
`

type UpdateIdentityDigestParams struct {
	Digest     string
	Version    int16
	Now        time.Time
	ID         string
	OldVersion int16
}

// CAS：只有版本仍为 old_version 的活跃行才改写（并发副本/绑定已改则 0 行，调用方跳过不计）。
func (q *Queries) UpdateIdentityDigest(ctx context.Context, arg UpdateIdentityDigestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentityDigest,
		arg.Digest,
		arg.Version,
		arg.Now,
		arg.ID,
		arg.OldVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIdentityProviderMeta = `-- name: UpdateIdentityProviderMeta :execrows
UPDATE identity SET provider_meta = $1, update_time = $2::timestamptz WHERE id = $3 AND delete_time IS NULL
`

type UpdateIdentityProviderMetaParams struct {
	ProviderMeta []byte
	UpdateTime   time.Time
	ID           string
}

func (q *Queries) UpdateIdentityProviderMeta(ctx context.Context, arg UpdateIdentityProviderMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentityProviderMeta, arg.ProviderMeta, arg.UpdateTime, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionAuthTime = `-- name: UpdateSessionAuthTime :execrows
UPDATE session SET auth_time = $1, update_time = $1
WHERE id = $2 AND revoke_time IS NULL AND refresh_expire_time > $1::timestamptz
`

type UpdateSessionAuthTimeParams struct {
	AuthTime time.Time
	ID       string
}

func (q *Queries) UpdateSessionAuthTime(ctx context.Context, arg UpdateSessionAuthTimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionAuthTime, arg.AuthTime, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE user_account SET display_name = $2, update_time = now() WHERE id = $1
RETURNING id, state, display_name, freeze_time, freeze_reason, freeze_actor_subject, freeze_actor_username, delete_time, purge_time, create_time, update_time
`

type UpdateUserDisplayNameParams struct {
	ID          string
	DisplayName *string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.DisplayName,
		&i.FreezeTime,
		&i.FreezeReason,
		&i.FreezeActorSubject,
		&i.FreezeActorUsername,
		&i.DeleteTime,
		&i.PurgeTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}
